#!/usr/bin/env ruby
require 'bundler/setup'
require 'beez/cli'

begin
  cli = ::Beez::CLI.instance
  cli.parse
  cli.run
rescue StandardError => e
  raise e if $DEBUG

  warn e.message
  warn e.backtrace.join("\n")
  exit 1
end
